services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "appdb"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "123456"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      CONFIG_PATH: /app/conf/confyg.yaml
      APP_SERVER_ENV: production
    volumes:
      - ./conf:/app/conf:ro
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  mysql_data:
